ktor {
    deployment {
        port = 8081
    }
    application {
        modules = [ com.mongodb.ApplicationKt.module ]
    }
    mongo {
        uri = ${?MONGO_URI}
        database = ${?MONGO_DATABASE}
    }
    huggingface {
        api {
            url = "https://router.huggingface.co/hf-inference/models/sentence-transformers/all-MiniLM-L6-v2/pipeline/feature-extraction"
            token = ${?HUGGINGFACE_TOKEN}
        }
    }
}