package com.devrel.wms.tool;

import com.devrel.wms.domain.Inventory;
import com.devrel.wms.domain.StockMovement;
import com.devrel.wms.service.InventoryService;
import com.devrel.wms.service.StockMovementService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.ai.tool.annotation.Tool;
import org.springframework.ai.tool.annotation.ToolParam;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public class InventoryAnalysisTool {

	private static final Logger logger = LoggerFactory.getLogger(InventoryAnalysisTool.class);

	private final InventoryService inventoryService;
	private final StockMovementService stockMovementService;
	private final ProductCodes productCodes;

	InventoryAnalysisTool(
			InventoryService inventoryService,
			StockMovementService stockMovementService,
			ProductCodes productCodes) {
		this.inventoryService = inventoryService;
		this.stockMovementService = stockMovementService;
		this.productCodes = productCodes;
	}

	@Tool(description = """
    	Get the current inventory quantity for a product, one entry per depositor.
    	Use this tool when you need to know the current available stock.
    """)
	public List<Inventory> getInventoryByProductCode(
			@ToolParam(description = ProductCodes.PRODUCT_CODE_PARAM) String productCode) {
		logger.info("##TOOL## - Calling Inventory Product Code for product {}", productCode);

		return inventoryService.findByProductCode(productCodes.require(productCode));
	}

	@Tool(description = """
    	Get the stock movement history for a product.
    	Use this tool to analyze recent inbound and outbound quantities and dates.
    """)
	public List<StockMovement> getStockMovement(
			@ToolParam(description = ProductCodes.PRODUCT_CODE_PARAM) String productCode) {
		logger.info("##TOOL## - Getting stock movement by product number {}", productCode);

		return stockMovementService.findByProductCode(productCodes.require(productCode));
	}

	@Tool(description = """
    	Get the stock movement history for a product of a specific depositor.
    	Use this tool to analyze recent inbound and outbound quantities and dates
    	of a single depositor.
    """)
	public List<StockMovement> getStockMovementByDepositor(
			@ToolParam(description = ProductCodes.PRODUCT_CODE_PARAM) String productCode,
			@ToolParam(description = ProductCodes.DEPOSITOR_CODE_PARAM) String depositorCode) {
		logger.info("##TOOL## - Getting stock movement by product {} and depositor {}", productCode, depositorCode);

		return stockMovementService.findByProductCodeAndDepositorCode(
				productCodes.require(productCode), depositorCode);
	}

	@Tool(description = """
    	Get the stock movements generated by a specific invoice.
    	Use this tool to discover which products and quantities were affected
    	by a completed outbound invoice.
    """)
	public List<StockMovement> getStockMovementByInvoiceNumber(
			@ToolParam(description = "Outbound invoice number") String invoiceNumber) {
		logger.info("##TOOL## - Getting stock movement by invoice number {}", invoiceNumber);

		return stockMovementService.findByInvoiceNumber(invoiceNumber);
	}
}
