package com.devrel.wms.tool;

import com.devrel.wms.entity.Inventory;
import com.devrel.wms.entity.Replenishment;
import com.devrel.wms.entity.StockMovement;
import com.devrel.wms.service.InventoryService;
import com.devrel.wms.service.ReplenishmentService;
import com.devrel.wms.service.StockMovementService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.ai.tool.annotation.Tool;
import org.springframework.ai.tool.annotation.ToolParam;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public class ReplenishmentTool {

	private static final Logger logger = LoggerFactory.getLogger(ReplenishmentTool.class);

	private final InventoryService inventoryService;
	private final StockMovementService stockMovementService;
	private final ReplenishmentService replenishmentService;


	public ReplenishmentTool(
			InventoryService inventoryService,
			StockMovementService stockMovementService,
			ReplenishmentService replenishmentService) {
		this.inventoryService = inventoryService;
		this.replenishmentService = replenishmentService;
		this.stockMovementService = stockMovementService;
	}

	@Tool(description = """
   		 Create a replenishment request when one or more products
    	 are expected to run out of stock soon.
    """)
	public Replenishment createReplenishment(
			@ToolParam(description = "Products and quantities that need replenishment")
			List<Replenishment.ReplenishmentItem> items,

			@ToolParam(description = "Short explanation of why replenishment is necessary")
			String message
	) {

		Replenishment replenishment =
				new Replenishment(null, items, message, Replenishment.Status.PENDING);

		return replenishmentService.save(replenishment);
	}

	@Tool(description = """
    	Get the current inventory quantity for a product.
    	Use this tool when you need to know the current available stock.
    """)
	public Inventory getInventoryByProductCode(
			@ToolParam(description = "Unique product code") String productCode) {
		logger.info("##TOOL## - Calling Inventory Product Code for product {}", productCode);
		return inventoryService.findByProductCode(productCode);
	}

	@Tool(description = """
    	Get the stock movement history for a product.
    	Use this tool to analyze recent inbound and outbound quantities and dates.
    """)
	public List<StockMovement> getStockMovement(
			@ToolParam(description = "Unique product code") String productCode) {
		logger.info("##TOOL## - Getting stock movement by product number {}", productCode);

		return stockMovementService.findByProductCode(productCode);
	}

	@Tool(description = """
    	Get the stock movements generated by a specific invoice.
    	Use this tool to discover which products and quantities were affected
    	by a completed outbound invoice.
    """)
	public List<StockMovement> getStockMovementByInvoiceNumber(
			@ToolParam(description = "Outbound invoice number") String invoiceNumber) {
		logger.info("##TOOL## - Getting stock movement by invoice number {}", invoiceNumber);

		return stockMovementService.findByInvoiceNumber(invoiceNumber);
	}

}
