app:
  mongodb:
    uri: ${MONGODB_URI}
    cryptSharedLibPath: ${CRYPT_PATH}
    keyVaultNamespace: encryption.__keyVault
    encryptedDatabaseName: hrsystem
    encryptedCollectionName: employees
    applicationName: devrel-tutorial-java-qe-springdata
logging:
  level:
    org.springframework.data.mongodb: DEBUG