spring:
  application:
    name: bankaccount

app:
  mongodb:
    uri: ${MONGO_URI}
    kmsProviderName: local
    keyVaultNamespace: encryption.__keyVault
    encryptedDatabaseName: digitalBank
    encryptedCollectionName: accounts
    cryptSharedLibPath: /Users/ricardomello/Documents/tools/mongo_crypt_shared_v1-macos-arm64-enterprise-8.0.0-rc17/lib/mongo_crypt_v1.dylib