spring.application.name=bankaccount
app.mongodb.uri=${MONGO_URI}
app.mongodb.kmsProviderName=local
app.mongodb.keyVaultNamespace=encryption.__keyVault
app.mongodb.encryptedDatabaseName=digitalBank
app.mongodb.encryptedCollectionName=accounts
app.mongodb.cryptSharedLibPath=${CRYPT_SHARED_LIB_PATH}