POST http://localhost:8080/inbound-invoice
Content-Type: application/json

{
  "number": "NF-1002",
  "items": [
    {
      "productCode": "01",
      "quantity": 200
    },
    {
      "productCode": "02",
      "quantity": 200
    },
    {
      "productCode": "03",
      "quantity": 200
    },
    {
      "productCode": "04",
      "quantity": 200
    }
  ]
}

### Check
POST http://localhost:8080/inbound-invoice/NF-1002/check
Content-Type: application/json

### Complete
POST http://localhost:8080/inbound-invoice/NF-1002/complete
Content-Type: application/json