### Create inventory
POST http://localhost:8080/inventory
Content-Type: application/json

{
  "productCode": "01",
  "quantity": 10
}

### Find inventory by product code
GET http://localhost:8080/inventory/04
Content-Type: application/json

### Increase stock
POST http://localhost:8080/inventory/01/movements?quantity=5
Content-Type: application/json

### Decrease stock
POST http://localhost:8080/inventory/01/movements?quantity=-5
Content-Type: application/json

### Decrease more than available. Expected to fail
POST http://localhost:8080/inventory/01/movements?quantity=-9999
Content-Type: application/json
