POST http://localhost:8080/inventory
Content-Type: application/json

{
  "productCode": "01",
  "quantity": 10
}

### Add Stock by product code. Use negative amount to decrease
GET http://localhost:8080/inventory/add/01/-5
Content-Type: application/json


### Increase by product code
GET http://localhost:8080/inventory/decrease/01/5
Content-Type: application/json

###
GET http://localhost:8080/products/code/02
Content-Type: application/json
