POST http://localhost:8080/outbound-invoice
Content-Type: application/json

{
  "number": "NF-2003",
  "depositor": {
    "id": "RICAS",
    "name": "Ricas Ltda",
    "email": "contact@ricas.com"
  },
  "items": [
    {
      "productCode": "01",
      "quantity": 200
    },
    {
      "productCode": "02",
      "quantity": 200
    },
    {
      "productCode": "03",
      "quantity": 200
    },
    {
      "productCode": "04",
      "quantity": 202
    }
  ]
}

### Update a pending invoice
PUT http://localhost:8080/outbound-invoice/NF-2003
Content-Type: application/json

{
  "items": [
    {
      "productCode": "01",
      "quantity": 500
    },
    {
      "productCode": "02",
      "quantity": 200
    }
  ]
}

### Check
POST http://localhost:8080/outbound-invoice/NF-2003/check
Content-Type: application/json

### Execute
POST http://localhost:8080/outbound-invoice/NF-2003/execute
Content-Type: application/json