POST http://localhost:8080/products
Content-Type: application/json

{
  "code": "01",
  "name": "Keyboard"
}


### Find By Id
GET http://localhost:8080/products/6a84c74c9cd67a896c32c951
Content-Type: application/json

###
GET http://localhost:8080/products/code/02
Content-Type: application/json
